# Generated by Django 5.1.2 on 2024-11-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='fecha_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
